# Generated by Django 4.1 on 2022-08-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.CharField(choices=[('S', 'Student'), ('P', 'Professional'), ('B', 'BusinessUser'), ('E', 'Expert')], max_length=1),
        ),
    ]
