# Generated by Django 4.1 on 2022-08-10 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('img', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('responsibilites', models.TextField()),
                ('expected_salary', models.IntegerField()),
                ('img', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('img', models.TextField(blank=True, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillitupcore.domain')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('img', models.TextField(blank=True, null=True)),
                ('subdomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillitupcore.subdomain')),
            ],
        ),
        migrations.CreateModel(
            name='TrendingTechIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('companies', models.TextField()),
                ('popularity', models.FloatField()),
                ('img', models.TextField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillitupcore.topic')),
            ],
        ),
        migrations.CreateModel(
            name='ReccomendationTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(max_length=200)),
                ('data_structure', models.SmallIntegerField(choices=[(0, 'Learner'), (1, 'Intermediate'), (2, 'Proficient'), (3, 'Expert')], default=0)),
                ('operating_system', models.SmallIntegerField(choices=[(0, 'Learner'), (1, 'Intermediate'), (2, 'Proficient'), (3, 'Expert')], default=0)),
                ('database_management', models.SmallIntegerField(choices=[(0, 'Learner'), (1, 'Intermediate'), (2, 'Proficient'), (3, 'Expert')], default=0)),
                ('computer_networks', models.SmallIntegerField(choices=[(0, 'Learner'), (1, 'Intermediate'), (2, 'Proficient'), (3, 'Expert')], default=0)),
                ('cryptography', models.SmallIntegerField(choices=[(0, 'Learner'), (1, 'Intermediate'), (2, 'Proficient'), (3, 'Expert')], default=0)),
                ('object_oriented_programming', models.SmallIntegerField(choices=[(0, 'Learner'), (1, 'Intermediate'), (2, 'Proficient'), (3, 'Expert')], default=0)),
                ('computer_graphics', models.SmallIntegerField(choices=[(0, 'Learner'), (1, 'Intermediate'), (2, 'Proficient'), (3, 'Expert')], default=0)),
                ('digital_electronics', models.SmallIntegerField(choices=[(0, 'Learner'), (1, 'Intermediate'), (2, 'Proficient'), (3, 'Expert')], default=0)),
                ('engineering_mathematics', models.SmallIntegerField(choices=[(0, 'Learner'), (1, 'Intermediate'), (2, 'Proficient'), (3, 'Expert')], default=0)),
                ('statistics', models.SmallIntegerField(choices=[(0, 'Learner'), (1, 'Intermediate'), (2, 'Proficient'), (3, 'Expert')], default=0)),
                ('communication', models.SmallIntegerField(choices=[(0, 'Learner'), (1, 'Intermediate'), (2, 'Proficient'), (3, 'Expert')], default=0)),
                ('english', models.SmallIntegerField(choices=[(0, 'Learner'), (1, 'Intermediate'), (2, 'Proficient'), (3, 'Expert')], default=0)),
                ('creativity', models.SmallIntegerField(choices=[(0, 'Learner'), (1, 'Intermediate'), (2, 'Proficient'), (3, 'Expert')], default=0)),
                ('hackathon', models.BooleanField(default=False)),
                ('hackathon_role', models.BooleanField(default=False)),
                ('creative_critical', models.BooleanField(default=False)),
                ('self_learning', models.BooleanField(default=False)),
                ('management_technical', models.BooleanField(default=False)),
                ('gaming', models.BooleanField(default=False)),
                ('art', models.BooleanField(default=False)),
                ('literature', models.BooleanField(default=False)),
                ('business', models.BooleanField(default=False)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillitupcore.profession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profession',
            name='technologies',
            field=models.ManyToManyField(to='skillitupcore.trendingtechit'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('place', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('attendees', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillitupcore.topic')),
            ],
        ),
        migrations.CreateModel(
            name='EducationalInstitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('img', models.TextField(blank=True, null=True)),
                ('students', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
                ('subdomains', models.ManyToManyField(blank=True, null=True, to='skillitupcore.subdomain')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('certificate', models.BooleanField(default=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('img', models.TextField(blank=True, null=True)),
                ('professions', models.ManyToManyField(to='skillitupcore.profession')),
                ('technologies', models.ManyToManyField(to='skillitupcore.trendingtechit')),
            ],
        ),
    ]
