# Generated by Django 4.1 on 2022-08-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillitupcore', '0002_alter_educationalinstitute_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
