# Generated by Django 4.1 on 2022-08-14 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillitupcore', '0003_profession_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reccomendationtest',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
