# Generated by Django 4.1 on 2022-08-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillitupcore', '0004_reccomendationtest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reccomendationtest',
            name='programming',
            field=models.SmallIntegerField(choices=[(0, 'Learner'), (1, 'Intermediate'), (2, 'Proficient'), (3, 'Expert')], default=0),
        ),
    ]
