# Generated by Django 4.1 on 2022-08-18 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skillitupcore', '0005_reccomendationtest_programming'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('certificate', models.BooleanField(default=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('img', models.TextField(blank=True, null=True)),
                ('professions', models.ManyToManyField(to='skillitupcore.profession')),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrendingTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('popularity', models.FloatField()),
                ('img', models.TextField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillitupcore.topic')),
            ],
        ),
        migrations.RenameModel(
            old_name='ReccomendationTest',
            new_name='RecommendationTest',
        ),
        migrations.RenameModel(
            old_name='TrendingTechIT',
            new_name='TrendingTech',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.AddField(
            model_name='expert',
            name='technologies',
            field=models.ManyToManyField(to='skillitupcore.trendingtech'),
        ),
        migrations.AddField(
            model_name='expert',
            name='tools',
            field=models.ManyToManyField(to='skillitupcore.trendingtool'),
        ),
        migrations.AddField(
            model_name='expert',
            name='topic',
            field=models.ManyToManyField(to='skillitupcore.topic'),
        ),
        migrations.AddField(
            model_name='expert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='technologies',
            field=models.ManyToManyField(to='skillitupcore.trendingtech'),
        ),
        migrations.AddField(
            model_name='course',
            name='tools',
            field=models.ManyToManyField(to='skillitupcore.trendingtool'),
        ),
        migrations.AddField(
            model_name='profession',
            name='tools',
            field=models.ManyToManyField(to='skillitupcore.trendingtool'),
        ),
    ]
