# Generated by Django 4.1 on 2022-08-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillitupcore', '0007_alter_profession_technologies_alter_profession_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='skillitupcore.trendingtech'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tools',
            field=models.ManyToManyField(blank=True, to='skillitupcore.trendingtool'),
        ),
    ]
