# Generated by Django 4.1 on 2022-08-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillitupcore', '0008_alter_course_technologies_alter_course_tools'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='expert',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expert',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='skillitupcore.trendingtech'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='tools',
            field=models.ManyToManyField(blank=True, to='skillitupcore.trendingtool'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='topic',
            field=models.ManyToManyField(blank=True, to='skillitupcore.topic'),
        ),
        migrations.AddField(
            model_name='expert',
            name='languages',
            field=models.ManyToManyField(default=True, to='skillitupcore.language'),
        ),
    ]
