# Generated by Django 4.1 on 2022-08-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillitupcore', '0009_language_expert_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='years',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
