# Generated by Django 4.1 on 2022-08-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillitupcore', '0011_alter_expert_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='available',
        ),
    ]
