# Generated by Django 4.1 on 2022-08-19 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillitupcore', '0012_remove_expert_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='technologies',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='tools',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='years',
        ),
    ]
