# Generated by Django 4.1 on 2022-08-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillitupcore', '0013_remove_expert_languages_remove_expert_technologies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='available',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='expert',
            name='languages',
            field=models.ManyToManyField(to='skillitupcore.language'),
        ),
        migrations.AddField(
            model_name='expert',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='skillitupcore.trendingtech'),
        ),
        migrations.AddField(
            model_name='expert',
            name='tools',
            field=models.ManyToManyField(blank=True, to='skillitupcore.trendingtool'),
        ),
        migrations.AddField(
            model_name='expert',
            name='years',
            field=models.IntegerField(default=0),
        ),
    ]
